version: "3"

services:
  server:
    restart: always
    environment:
      - TORCH_CUDA=cu116
      - API_KEY=${API_KEY}
    build:
      context: .
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
