version: "3"

services:
  server:
    restart: always
    environment:
      - TORCH_CUDA=cu116
      - API_KEY=${API_KEY}
      - PYTHONUNBUFFERED=TRUE
    build:
      context: .
    ports:
      - 8080:8080
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
